const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{Audio: 0},
	{particles_blue: 0},
	{particles_player: 0},
	{particles_red: 0},
	{particles_yellow: 0},
	{background: 0},
	{turningSpeed: 0},
	{turningWait: 0},
	{isTurning: 0},
	{Tween: 0},
	{player: 0},
	{Bullet: 0},
	{ring: 0},
	{ringSpawner: 0},
	{button_left: 0},
	{button_right: 0},
	{Wrap: 0},
	{star: 0},
	{button_exit: 0},
	{button_rangkuman: 0},
	{button_youtube: 0},
	{cara_main: 0},
	{Sine: 0},
	{judul: 0},
	{logo_ejies: 0},
	{mainkan: 0},
	{papan_skor: 0},
	{DragDrop: 0},
	{rangkuman_materi: 0},
	{ring2: 0},
	{button_back: 0},
	{txt_go: 0},
	{txt_highScore: 0},
	{txt_ready: 0},
	{txt_score: 0},
	{main: 0},
	{soal1: 0},
	{"1a": 0},
	{"1b": 0},
	{"1c": 0},
	{"1d": 0},
	{"2a": 0},
	{"2b": 0},
	{"2c": 0},
	{"2d": 0},
	{soal2: 0},
	{"3a": 0},
	{"3b": 0},
	{"3c": 0},
	{"3d": 0},
	{soal3: 0},
	{"4a": 0},
	{"4b": 0},
	{"4c": 0},
	{"4d": 0},
	{soal4: 0},
	{"5a": 0},
	{"5b": 0},
	{"5c": 0},
	{"5d": 0},
	{soal5: 0},
	{fam_particles: 0},
	{spawnSpeed: 0},
	{ringSpeed: 0},
	{gameOver: 0},
	{score: 0},
	{highScore: 0},
	{levelUp: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	particles_blue: class extends self.IParticlesInstance {},
	particles_player: class extends self.IParticlesInstance {},
	particles_red: class extends self.IParticlesInstance {},
	particles_yellow: class extends self.IParticlesInstance {},
	background: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	ring: class extends self.ISpriteInstance {},
	ringSpawner: class extends self.ISpriteInstance {},
	button_left: class extends self.ISpriteInstance {},
	button_right: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	button_exit: class extends self.ISpriteInstance {},
	button_rangkuman: class extends self.ISpriteInstance {},
	button_youtube: class extends self.ISpriteInstance {},
	cara_main: class extends self.ISpriteInstance {},
	judul: class extends self.ISpriteInstance {},
	logo_ejies: class extends self.ISpriteInstance {},
	mainkan: class extends self.ISpriteInstance {},
	papan_skor: class extends self.ISpriteInstance {},
	rangkuman_materi: class extends self.ISpriteInstance {},
	ring2: class extends self.ISpriteInstance {},
	button_back: class extends self.ISpriteInstance {},
	txt_go: class extends self.ITextInstance {},
	txt_highScore: class extends self.ITextInstance {},
	txt_ready: class extends self.ITextInstance {},
	txt_score: class extends self.ITextInstance {},
	main: class extends self.ITextInstance {},
	soal1: class extends self.ISpriteInstance {},
	_1a: class extends self.ISpriteInstance {},
	_1b: class extends self.ISpriteInstance {},
	_1c: class extends self.ISpriteInstance {},
	_1d: class extends self.ISpriteInstance {},
	_2a: class extends self.ISpriteInstance {},
	_2b: class extends self.ISpriteInstance {},
	_2c: class extends self.ISpriteInstance {},
	_2d: class extends self.ISpriteInstance {},
	soal2: class extends self.ISpriteInstance {},
	_3a: class extends self.ISpriteInstance {},
	_3b: class extends self.ISpriteInstance {},
	_3c: class extends self.ISpriteInstance {},
	_3d: class extends self.ISpriteInstance {},
	soal3: class extends self.ISpriteInstance {},
	_4a: class extends self.ISpriteInstance {},
	_4b: class extends self.ISpriteInstance {},
	_4c: class extends self.ISpriteInstance {},
	_4d: class extends self.ISpriteInstance {},
	soal4: class extends self.ISpriteInstance {},
	_5a: class extends self.ISpriteInstance {},
	_5b: class extends self.ISpriteInstance {},
	_5c: class extends self.ISpriteInstance {},
	_5d: class extends self.ISpriteInstance {},
	soal5: class extends self.ISpriteInstance {},
	fam_particles: class extends self.IParticlesInstance {}
}